### ISSUE TITLE
fail to reproduce demo locally

### ISSUE THREAD

**Issue by jianguda** [IAIK/interruptjs#1]
Hey @mlq 
I am trying to reproduce the demo locally but it does not work normally. I tested on latest Chrome and Firefox but both failed. However, the live demo is very successful.

Could you please help check this issue? or give me some advice for this? Thanks!

**Comment by mlq** [comment]
Hi! The live demo code should be the same as in the repository. Did you adapted anything?

**Comment by jianguda** [comment]
No, I did not. I just download the repo and open the `index.html`. Am I right?

**Comment by orestisfl** [comment]
@jianguda You'll probably want to start a local server like with `python3 -m http.server`

**Comment by jianguda** [comment]
@orestisfl Thanks for your help!
